package org.wella.entity;

import java.util.Date;

public class Bankcard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_bankcard.bankcard_id
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    private Long bankcardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_bankcard.user_id
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_bankcard.bank_name
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_bankcard.add_time
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_bankcard.bank_account
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    private String bankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_bankcard.open_address
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    private String openAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_bankcard.bankcard_id
     *
     * @return the value of wa_bankcard.bankcard_id
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public Long getBankcardId() {
        return bankcardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_bankcard.bankcard_id
     *
     * @param bankcardId the value for wa_bankcard.bankcard_id
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public void setBankcardId(Long bankcardId) {
        this.bankcardId = bankcardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_bankcard.user_id
     *
     * @return the value of wa_bankcard.user_id
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_bankcard.user_id
     *
     * @param userId the value for wa_bankcard.user_id
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_bankcard.bank_name
     *
     * @return the value of wa_bankcard.bank_name
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_bankcard.bank_name
     *
     * @param bankName the value for wa_bankcard.bank_name
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_bankcard.add_time
     *
     * @return the value of wa_bankcard.add_time
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_bankcard.add_time
     *
     * @param addTime the value for wa_bankcard.add_time
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_bankcard.bank_account
     *
     * @return the value of wa_bankcard.bank_account
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_bankcard.bank_account
     *
     * @param bankAccount the value for wa_bankcard.bank_account
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_bankcard.open_address
     *
     * @return the value of wa_bankcard.open_address
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public String getOpenAddress() {
        return openAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_bankcard.open_address
     *
     * @param openAddress the value for wa_bankcard.open_address
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public void setOpenAddress(String openAddress) {
        this.openAddress = openAddress == null ? null : openAddress.trim();
    }
}