package org.wella.entity;

/**
 * 码表
 */
public class Option {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_option.id
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_option.code_value
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    private String codeValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_option.code_key
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    private String codeKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_option.code_order
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    private Short codeOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_option.code_column
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    private String codeColumn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_option.code_table
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    private String codeTable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_option.id
     *
     * @return the value of wa_option.id
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_option.id
     *
     * @param id the value for wa_option.id
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_option.code_value
     *
     * @return the value of wa_option.code_value
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public String getCodeValue() {
        return codeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_option.code_value
     *
     * @param codeValue the value for wa_option.code_value
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public void setCodeValue(String codeValue) {
        this.codeValue = codeValue == null ? null : codeValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_option.code_key
     *
     * @return the value of wa_option.code_key
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public String getCodeKey() {
        return codeKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_option.code_key
     *
     * @param codeKey the value for wa_option.code_key
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public void setCodeKey(String codeKey) {
        this.codeKey = codeKey == null ? null : codeKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_option.code_order
     *
     * @return the value of wa_option.code_order
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public Short getCodeOrder() {
        return codeOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_option.code_order
     *
     * @param codeOrder the value for wa_option.code_order
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public void setCodeOrder(Short codeOrder) {
        this.codeOrder = codeOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_option.code_column
     *
     * @return the value of wa_option.code_column
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public String getCodeColumn() {
        return codeColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_option.code_column
     *
     * @param codeColumn the value for wa_option.code_column
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public void setCodeColumn(String codeColumn) {
        this.codeColumn = codeColumn == null ? null : codeColumn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_option.code_table
     *
     * @return the value of wa_option.code_table
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public String getCodeTable() {
        return codeTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_option.code_table
     *
     * @param codeTable the value for wa_option.code_table
     *
     * @mbggenerated Thu Jun 08 10:48:16 CST 2017
     */
    public void setCodeTable(String codeTable) {
        this.codeTable = codeTable == null ? null : codeTable.trim();
    }
}