package org.wella.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 * 提现实体类
 */
public class Withdraw {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_withdraw.withdraw_id
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    private Long withdrawId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_withdraw.money_id
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    private Long moneyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_withdraw.user_id
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_withdraw.withdraw_money
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    private BigDecimal withdrawMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_withdraw.withdraw_name
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    private String withdrawName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_withdraw.withdraw_bank
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    private String withdrawBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_withdraw.account
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_withdraw.withdraw_state
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    private Byte withdrawState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_withdraw.withdraw_date
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    private Date withdrawDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_withdraw.withdraw_ip
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    private String withdrawIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_withdraw.mgr_user_id
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    private Long mgrUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_withdraw.mgr_date
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    private Date mgrDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_withdraw.content
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wa_withdraw.mgr_ip
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    private String mgrIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_withdraw.withdraw_id
     *
     * @return the value of wa_withdraw.withdraw_id
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public Long getWithdrawId() {
        return withdrawId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_withdraw.withdraw_id
     *
     * @param withdrawId the value for wa_withdraw.withdraw_id
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public void setWithdrawId(Long withdrawId) {
        this.withdrawId = withdrawId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_withdraw.money_id
     *
     * @return the value of wa_withdraw.money_id
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public Long getMoneyId() {
        return moneyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_withdraw.money_id
     *
     * @param moneyId the value for wa_withdraw.money_id
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public void setMoneyId(Long moneyId) {
        this.moneyId = moneyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_withdraw.user_id
     *
     * @return the value of wa_withdraw.user_id
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_withdraw.user_id
     *
     * @param userId the value for wa_withdraw.user_id
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_withdraw.withdraw_money
     *
     * @return the value of wa_withdraw.withdraw_money
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public BigDecimal getWithdrawMoney() {
        return withdrawMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_withdraw.withdraw_money
     *
     * @param withdrawMoney the value for wa_withdraw.withdraw_money
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public void setWithdrawMoney(BigDecimal withdrawMoney) {
        this.withdrawMoney = withdrawMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_withdraw.withdraw_name
     *
     * @return the value of wa_withdraw.withdraw_name
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public String getWithdrawName() {
        return withdrawName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_withdraw.withdraw_name
     *
     * @param withdrawName the value for wa_withdraw.withdraw_name
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public void setWithdrawName(String withdrawName) {
        this.withdrawName = withdrawName == null ? null : withdrawName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_withdraw.withdraw_bank
     *
     * @return the value of wa_withdraw.withdraw_bank
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public String getWithdrawBank() {
        return withdrawBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_withdraw.withdraw_bank
     *
     * @param withdrawBank the value for wa_withdraw.withdraw_bank
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public void setWithdrawBank(String withdrawBank) {
        this.withdrawBank = withdrawBank == null ? null : withdrawBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_withdraw.account
     *
     * @return the value of wa_withdraw.account
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_withdraw.account
     *
     * @param account the value for wa_withdraw.account
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_withdraw.withdraw_state
     *
     * @return the value of wa_withdraw.withdraw_state
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public Byte getWithdrawState() {
        return withdrawState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_withdraw.withdraw_state
     *
     * @param withdrawState the value for wa_withdraw.withdraw_state
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public void setWithdrawState(Byte withdrawState) {
        this.withdrawState = withdrawState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_withdraw.withdraw_date
     *
     * @return the value of wa_withdraw.withdraw_date
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public Date getWithdrawDate() {
        return withdrawDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_withdraw.withdraw_date
     *
     * @param withdrawDate the value for wa_withdraw.withdraw_date
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public void setWithdrawDate(Date withdrawDate) {
        this.withdrawDate = withdrawDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_withdraw.withdraw_ip
     *
     * @return the value of wa_withdraw.withdraw_ip
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public String getWithdrawIp() {
        return withdrawIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_withdraw.withdraw_ip
     *
     * @param withdrawIp the value for wa_withdraw.withdraw_ip
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public void setWithdrawIp(String withdrawIp) {
        this.withdrawIp = withdrawIp == null ? null : withdrawIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_withdraw.mgr_user_id
     *
     * @return the value of wa_withdraw.mgr_user_id
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public Long getMgrUserId() {
        return mgrUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_withdraw.mgr_user_id
     *
     * @param mgrUserId the value for wa_withdraw.mgr_user_id
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public void setMgrUserId(Long mgrUserId) {
        this.mgrUserId = mgrUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_withdraw.mgr_date
     *
     * @return the value of wa_withdraw.mgr_date
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public Date getMgrDate() {
        return mgrDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_withdraw.mgr_date
     *
     * @param mgrDate the value for wa_withdraw.mgr_date
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public void setMgrDate(Date mgrDate) {
        this.mgrDate = mgrDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_withdraw.content
     *
     * @return the value of wa_withdraw.content
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_withdraw.content
     *
     * @param content the value for wa_withdraw.content
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wa_withdraw.mgr_ip
     *
     * @return the value of wa_withdraw.mgr_ip
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public String getMgrIp() {
        return mgrIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wa_withdraw.mgr_ip
     *
     * @param mgrIp the value for wa_withdraw.mgr_ip
     *
     * @mbggenerated Fri Jun 02 15:01:16 CST 2017
     */
    public void setMgrIp(String mgrIp) {
        this.mgrIp = mgrIp == null ? null : mgrIp.trim();
    }
}