
package com.wellassist.pay.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BankB2bPayService", targetNamespace = "http://service.pay.wellassist.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankB2BPayService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "b2bPay")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "b2bPay", targetNamespace = "http://service.pay.wellassist.com/", className = "com.wellassist.pay.client.B2BPay")
    @ResponseWrapper(localName = "b2bPayResponse", targetNamespace = "http://service.pay.wellassist.com/", className = "com.wellassist.pay.client.B2BPayResponse")
    @Action(input = "http://service.pay.wellassist.com/BankB2bPayService/b2bPayRequest", output = "http://service.pay.wellassist.com/BankB2bPayService/b2bPayResponse")
    public String b2BPay(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
